"use client";
import {useState} from 'react';
import {Leaf,ScanLine,MapPin,ClipboardList,Award,UserRound,Bell,Sprout,ShieldCheck,WifiOff} from 'lucide-react';
import {Button} from '@/components/ui/button';
import Workspace from './workspace';
const pages=['Home','Scan & guidance','Reports','Rewards & impact','Profile & help'];
const icons=[Leaf,ScanLine,ClipboardList,Award,UserRound];
export default function Home(){
const [page,setPage]=useState('Home'),[notice,setNotice]=useState('');
return <div className="recity"><aside><a className="brand" href="/"><Leaf/> RECITY</a><small>WASTE INTELLIGENCE</small><p className="navlabel">YOUR WORKSPACE</p><nav>{pages.map((p,i)=>{const Icon=icons[i];return <button key={p} className={p===page?'active':''} onClick={()=>setPage(p)}><Icon size={20}/>{p}</button>})}</nav><div className="sidebottom"><Sprout/><h3>Less waste.<br/>More possibility.</h3><p>A useful next step for every kind of waste.</p></div></aside><div className="body"><header><span>RECITY / Citizen</span><div>English <button aria-label="Notifications" onClick={()=>setNotice('No notifications yet. Live notification setup is pending.')}><Bell size={20}/></button><b>OO</b></div></header><div className="preview"><ShieldCheck size={16}/>Development build · Connections and workflows are being verified.</div><main>{notice&&<div role="status" className="notice">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss">×</button></div>}
{page!=='Home'?<Workspace page={page}/>:page==='Home'?<><section className="hero"><div><p className="eyebrow">SMALL ACTIONS. A CLEANER TOMORROW.</p><h1>See possibility.<br/><em>Make a difference.</em></h1><p>Understand what you’re throwing away.<br/>Find its next use, or help it reach the right hands.</p><div className="buttons"><Button onClick={()=>setPage('Scan & guidance')}><ScanLine/>Scan waste</Button><Button variant="outline" onClick={()=>setPage('Report waste')}><MapPin/>Report waste</Button></div></div></section><div className="heading"><h2>What would you like to do?</h2><span>Start with one small step</span></div><div className="cards">{[{title:'Know your waste',text:'Identify the material and understand the appropriate next step.',target:'Scan & guidance',icon:ScanLine},{title:'Report a problem',text:'Add a photo and location. Follow your report through collection.',target:'Report waste',icon:MapPin},{title:'See your contribution',text:'Verified actions and clear impact, with estimates kept transparent.',target:'Rewards & impact',icon:Award}].map(c=><button className="card" key={c.title} onClick={()=>setPage(c.target)}><span className="icon"><c.icon/></span><h3>{c.title}</h3><p>{c.text}</p><strong>{c.target}</strong></button>)}</div><div className="columns"><section className="panel"><div className="heading"><h2>Your reports</h2><button onClick={()=>setPage('Reports')}>View all</button></div><div className="empty"><ClipboardList/><h3>Your first report starts here</h3><p>Once connected, your reports and collection progress will appear here.</p><Button variant="outline" onClick={()=>setPage('Report waste')}>Report waste</Button></div></section><section className="reuse"><p className="eyebrow">GIVE WASTE ANOTHER LIFE</p><Sprout/><h2>Useful doesn’t<br/>have to mean new.</h2><p>Get a suitable reuse project, a materials list, and clear instructions to follow at your own pace.</p><button onClick={()=>setPage('Scan & guidance')}>Start with a scan</button></section></div><div className="coverage"><ShieldCheck/><div><h3>Every kind of waste deserves a response.</h3><p>Recyclables · Organic · Electronic · Sanitary · Hazardous · Construction · Bulky · Animal remains · Mixed or unknown</p></div></div></>:null}
<footer><span>RECITY · Shared responsibility</span><div><button onClick={()=>setPage('Collector')}>Collector workspace</button><button onClick={()=>setPage('Municipal')}>Municipal workspace</button></div></footer></main></div><nav className="mobile">{pages.map((p,i)=>{const Icon=icons[i];return <button key={p} onClick={()=>setPage(p)} className={page===p?'active':''}><Icon size={20}/>{['Home','Scan','Reports','Impact','Profile'][i]}</button>})}</nav></div>}



