"use client";
import {useEffect,useState,useCallback} from 'react';
import {supabase} from '@/lib/supabase';
import {drafts,saveDraft,sendDraft,removeDraft,type Draft} from '@/lib/offline';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Leaf,ShieldCheck,MapPin,WifiOff,ScanLine,ClipboardList} from 'lucide-react';
import ReuseGuide from './reuse-guide';
import type {Observation} from '@/lib/decision';
type Profile={id:string;display_name:string;role:string;on_duty:boolean;service_area:string;capabilities:string[]};
type Report={id:string;description:string;landmark:string;latitude:number;longitude:number;status:string;category:string;service_area:string;photo_path:string;collector_id:string|null;created_at:string};
type Offer={id:string;report_id:string;status:string;expires_at:string};
type Event={id:number;action:string;note:string;created_at:string};
type Analysis={analysis_id:string;observation:Observation;decision:{score:number|null;label:string;route:string;reuseAllowed:boolean;policyVersion:string}};
const steps=['reported','verified','assigned','collected','resolved'];
function explain(error:unknown){const s=error instanceof Error?error.message:String(error);return /relation|schema cache|does not exist/.test(s)?'Database setup is pending. Run the RECITY migration in the new Supabase project.':/anonymous.*disabled/i.test(s)?'Enable anonymous sign-ins in your new Supabase project to continue.':s;}
function safeFile(f:File){if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw Error('Choose a JPEG, PNG or WebP photo.');if(f.size>3*1024*1024)throw Error('Choose a photo smaller than 3 MB.');}
function Photo({path}:{path:string}){const [src,setSrc]=useState('');useEffect(()=>{let active=true;supabase.storage.from('report-media').createSignedUrl(path,300).then(r=>{if(active)setSrc(r.data?.signedUrl||'')});return()=>{active=false}},[path]);return src?<img className="reportphoto" src={src} alt="Report evidence"/>:<div className="soft">Photo unavailable</div>}
export default function Workspace({page}:{page:string}){
 const [profile,setProfile]=useState<Profile|null>(null),[uid,setUid]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reports,setReports]=useState<Report[]>([]),[offers,setOffers]=useState<Offer[]>([]),[selected,setSelected]=useState<Report|null>(null),[events,setEvents]=useState<Event[]>([]),[queue,setQueue]=useState<Draft[]>([]),[file,setFile]=useState<File|null>(null),[image,setImage]=useState(''),[analysis,setAnalysis]=useState<Analysis|null>(null),[name,setName]=useState(''),[token,setToken]=useState(''),[area,setArea]=useState(''),[description,setDescription]=useState(''),[landmark,setLandmark]=useState(''),[coordinates,setCoordinates]=useState(''),[confirmed,setConfirmed]=useState(false),[note,setNote]=useState(''),[collectors,setCollectors]=useState<Profile[]>([]),[points,setPoints]=useState(0),[proof,setProof]=useState<File|null>(null),[proofPaths,setProofPaths]=useState<string[]>([]),[capabilities,setCapabilities]=useState<string[]>(['recyclable']),[newCode,setNewCode]=useState('');
 const categories=['recyclable','organic','electronic','sanitary','hazardous','construction','bulky','animal_remains','mixed','unknown'];
 const load=useCallback(async()=>{const {data:{session}}=await supabase.auth.getSession();setUid(session?.user.id||'');if(!session)return;const p=await supabase.from('profiles').select('*').eq('id',session.user.id).single();if(p.error)throw Error(p.error.message);setProfile(p.data);setName(old=>old||p.data.display_name);const r=await supabase.from('reports').select('*').order('created_at',{ascending:false}).limit(100);if(r.error)throw Error(r.error.message);setReports(r.data||[]);const o=await supabase.from('job_offers').select('*').eq('collector_id',session.user.id).eq('status','pending').gt('expires_at',new Date().toISOString());if(o.error)throw Error(o.error.message);setOffers(o.data||[]);const ledger=await supabase.from('reward_ledger').select('points');setPoints((ledger.data||[]).reduce((s,r)=>s+r.points,0));setQueue((await drafts()).filter(d=>d.owner===session.user.id));if(p.data.role==='administrator'){const c=await supabase.from('profiles').select('*').eq('role','collector');setCollectors(c.data||[])}},[]);
 useEffect(()=>{load().catch(e=>setMessage(explain(e)));const {data:{subscription}}=supabase.auth.onAuthStateChange(()=>{setTimeout(()=>load().catch(e=>setMessage(explain(e))),0)});const timer=setInterval(()=>{if(document.visibilityState==='visible')load().catch(()=>{})},15000);return()=>{subscription.unsubscribe();clearInterval(timer)}},[load]);
 useEffect(()=>{setSelected(null);setMessage('')},[page]);
 async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(explain(e))}finally{setBusy(false)}}
 async function rpc(name:string,args:Record<string,unknown>){const r=await supabase.rpc(name,args);if(r.error)throw Error(r.error.message);await load();return r.data;}
 async function openReport(r:Report){setSelected(r);const e=await supabase.from('report_events').select('*').eq('report_id',r.id).order('created_at');if(e.error)throw Error(e.error.message);setEvents(e.data||[]);const p=await supabase.from('collection_proof').select('photo_path').eq('report_id',r.id);setProofPaths((p.data||[]).map(x=>x.photo_path));}
 async function sync(){const {data:{session}}=await supabase.auth.getSession();if(!session)return;for(const d of await drafts()){if(d.owner!==session.user.id)continue;await sendDraft(d);await removeDraft(d.id)}await load();setMessage('Queued reports synchronized.');}
 useEffect(()=>{const online=()=>{sync().catch(e=>setMessage(explain(e)))};window.addEventListener('online',online);return()=>window.removeEventListener('online',online)},[]);
 async function pick(f:File|undefined){if(!f)return;safeFile(f);setFile(f);setAnalysis(null);if(image)URL.revokeObjectURL(image);setImage(URL.createObjectURL(f));}
 const sessionPanel=<section className="panel"><ShieldCheck/><h2>Start your private RECITY session</h2><p>No email or phone number needed. This browser will remember your account. Clearing browser data can remove access; recovery setup is still pending.</p><Button disabled={busy} onClick={()=>action(async()=>{const r=await supabase.auth.signInAnonymously();if(r.error)throw Error(r.error.message);await load()})}>{busy?'Connecting…':'Continue on this device'}</Button></section>;
 return <><div className="heading"><div><p className="eyebrow">{profile?`${profile.display_name} · ${profile.role}`:'YOUR RECITY'}</p><h1>{page}</h1></div>{profile&&<Button variant="outline" onClick={()=>action(load)} disabled={busy}>Refresh</Button>}</div>{message&&<div role="status" className="notice">{message}</div>}{!profile&&sessionPanel}
 {page==='Scan & guidance'&&<div className="columns"><section className="panel"><label className="upload">{image?<img src={image} alt="Selected waste"/>:<><ScanLine size={40}/><h2>What’s in your hands?</h2><p>Choose one clear photo</p></>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>action(()=>pick(e.target.files?.[0]))}/></label><Button disabled={!file||!profile||busy} onClick={()=>action(async()=>{const img=await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result));f.onerror=()=>reject(Error('Could not read image'));f.readAsDataURL(file!)});const {data:{session}}=await supabase.auth.getSession();const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({image:img})});const result=await r.json() as Analysis & {error?:string};if(!r.ok)throw Error(result.error||'Analysis failed');setAnalysis(result)})}>{busy?'Assessing…':'Analyze waste'}</Button><p>Your image is sent to Groq for assessment when you analyze it.</p></section><section className="panel">{analysis?<><h2>{analysis.observation.object}</h2><p>{analysis.observation.material} · {analysis.observation.condition}</p><div className="hazard"><strong>{analysis.decision.score===null?'—':`${analysis.decision.score}/100`}</strong><span>{analysis.decision.label}<br/>Estimated hazard score</span></div><p>{analysis.observation.reason}</p><small>Experimental screening policy; not a measured probability or a safety guarantee.</small><div className="soft">{analysis.decision.route}</div>{analysis.observation.questions.map(q=><p key={q}>• {q}</p>)}{analysis.decision.reuseAllowed&&<ReuseGuide key={analysis.analysis_id} analysisId={analysis.analysis_id}/>}</>:<><Leaf/><h2>Guidance, with reasons.</h2><p>Material, condition, estimated hazard, and an appropriate next step.</p><div className="soft">Unclear images receive questions—not invented certainty. No result is displayed until a real analysis succeeds.</div></>}</section></div>}
 {page==='Report waste'&&<section className="panel form"><label>Photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>action(()=>pick(e.target.files?.[0]))}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={3000}/></label><label>Waste coordinates<input value={coordinates} onChange={e=>{setCoordinates(e.target.value);setConfirmed(false)}} placeholder="Latitude, longitude"/></label><Button variant="outline" disabled={busy} onClick={()=>action(async()=>{const p=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{timeout:15000,maximumAge:0}));setCoordinates(`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`);setConfirmed(false);setMessage(`Location captured, reported accuracy about ${Math.round(p.coords.accuracy)} metres. Confirm this marks the waste.`)})}><MapPin/>Use my location</Button>{coordinates&&<a target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(coordinates)}`}>Check this location in Google Maps</a>}<label>Landmark<input value={landmark} onChange={e=>setLandmark(e.target.value)} maxLength={300}/></label><label>Service area / ward<input value={area} onChange={e=>setArea(e.target.value)} maxLength={100} placeholder="Municipal service area, if known"/></label><label className="checkline"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>I confirm the coordinates mark the waste.</label><Button disabled={!profile||busy} onClick={()=>action(async()=>{if(!file)throw Error('Add a photo.');safeFile(file);const parts=coordinates.split(',').map(Number);if(parts.length!==2||parts.some(n=>!Number.isFinite(n))||Math.abs(parts[0])>90||Math.abs(parts[1])>180||!confirmed)throw Error('Enter valid coordinates and confirm the waste location.');if(description.trim().length<3)throw Error('Add a short description.');const d:Draft={id:crypto.randomUUID(),description:description.trim(),landmark,lat:parts[0],lon:parts[1],area:area.trim(),file,owner:uid};await saveDraft(d);setQueue(await drafts());if(!navigator.onLine){setMessage('Saved on this device. Not yet sent to a collector.');return}await sendDraft(d);await removeDraft(d.id);setDescription('');setFile(null);await load();setMessage('Report submitted. It awaits screening; no collector has accepted it yet.')})}>{busy?'Saving…':'Submit report'}</Button><p>Unknown waste is accepted for review. A saved offline draft is not a delivered complaint.</p></section>}
 {['Reports','Collector','Municipal'].includes(page)&&profile&&<>{page==='Collector'&&profile.role!=='collector'?<div className="panel form"><h2>Activate collector access</h2><label>Single-use invitation code<input value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><Button disabled={busy} onClick={()=>action(async()=>{await rpc('activate_collector',{p_token:token});setToken('');setMessage('Collector activated.')})}>Activate</Button></div>:page==='Municipal'&&profile.role!=='administrator'?<section className="panel"><h2>Administrator access required</h2><p>Your role must be assigned through trusted project setup. This screen cannot grant access.</p></section>:<>
 {page==='Collector'&&<section className="panel"><label className="checkline"><Checkbox checked={profile.on_duty} onCheckedChange={v=>action(async()=>{await rpc('save_profile',{p_name:profile.display_name,p_on_duty:v===true})})}/>On duty</label><h2>Job offers</h2>{offers.length===0?<p>No pending offers.</p>:offers.map(o=><div className="job" key={o.id}><p>{reports.find(r=>r.id===o.report_id)?.description||'Collection job'}</p><Button disabled={busy} onClick={()=>action(async()=>{await rpc('respond_offer',{p_offer:o.id,p_accept:true});setMessage('Job accepted.')})}>Accept</Button><Button variant="outline" disabled={busy} onClick={()=>action(async()=>{await rpc('respond_offer',{p_offer:o.id,p_accept:false});setMessage('Offer declined; visible to municipality.')})}>Decline</Button></div>)}</section>}
 {page==='Municipal'&&<section className="panel form"><h2>Add a collector</h2><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Service area<input value={area} onChange={e=>setArea(e.target.value)}/></label><p>Authorized waste categories</p><div className="categorychecks">{categories.map(c=><label className="checkline" key={c}><Checkbox checked={capabilities.includes(c)} onCheckedChange={v=>setCapabilities(v?[...capabilities,c]:capabilities.filter(x=>x!==c))}/>{c.replaceAll('_',' ')}</label>)}</div><Button disabled={busy} onClick={()=>action(async()=>{const code=await rpc('create_collector_invitation',{p_name:name,p_area:area,p_capabilities:capabilities});setNewCode(code)})}>Create one-time invitation</Button>{newCode&&<div className="soft"><p>Share privately with the intended collector. Expires in 24 hours.</p><code style={{overflowWrap:'anywhere'}}>{newCode}</code><Button variant="outline" onClick={()=>action(async()=>{await navigator.clipboard.writeText(newCode);setMessage('Invitation copied.')})}>Copy code</Button></div>}</section>}
 <div className="columns"><section className="panel"><h2>{page==='Collector'?'Assigned jobs':'Reports'}</h2>{reports.filter(r=>page!=='Collector'||r.collector_id===uid).length===0?<div className="empty"><ClipboardList/><p>No reports yet.</p></div>:reports.filter(r=>page!=='Collector'||r.collector_id===uid).map(r=><button className="reportrow" key={r.id} onClick={()=>action(()=>openReport(r))}><span>{r.description}</span><small>{r.service_area} · {r.status}</small></button>)}</section><section className="panel">{selected?<><Photo path={selected.photo_path}/><h2>{selected.description}</h2><p>{selected.landmark}</p><a href={`https://www.google.com/maps/dir/?api=1&destination=${selected.latitude},${selected.longitude}`} target="_blank" rel="noreferrer">Get directions in Google Maps</a><p className="soft">{selected.status} · {selected.category.replaceAll('_',' ')}</p><ol className="events">{events.map(e=><li key={e.id}><strong>{e.action.replaceAll('_',' ')}</strong><small>{new Date(e.created_at).toLocaleString()}</small><p>{e.note}</p></li>)}</ol>{proofPaths.map(p=><Photo key={p} path={p}/>)}<label className="field">Decision / collection note<textarea value={note} onChange={e=>setNote(e.target.value)}/></label>
 {profile.role==='administrator'&&<div className="controls">{selected.status==='reported'&&<Button disabled={busy} onClick={()=>action(async()=>{await rpc('transition_report',{p_report:selected.id,p_action:'verified',p_note:note});setSelected(null)})}>Verify manually</Button>}{selected.status==='collected'&&<Button disabled={busy} onClick={()=>action(async()=>{await rpc('transition_report',{p_report:selected.id,p_action:'resolved',p_note:note});setSelected(null)})}>Accept evidence & resolve</Button>}{['verified','blocked','reopened'].includes(selected.status)&&<><p>Eligible on-duty collectors</p>{collectors.filter(c=>c.on_duty&&c.service_area===selected.service_area&&c.capabilities.includes(selected.category)).map(c=><Button key={c.id} disabled={busy} onClick={()=>action(async()=>{await rpc('offer_job',{p_report:selected.id,p_collector:c.id});setMessage('Job offered. Push delivery is not connected yet; it appears in the collector inbox.')})}>Offer to {c.display_name}</Button>)}</>}</div>}
 {profile.role==='collector'&&selected.collector_id===uid&&selected.status==='assigned'&&<div className="form"><label>Fresh collection proof<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>setProof(e.target.files?.[0]||null)}/></label><Button disabled={busy} onClick={()=>action(async()=>{if(!proof)throw Error('Add a completion photo');safeFile(proof);const path=`${uid}/${crypto.randomUUID()}.jpg`;const u=await supabase.storage.from('report-media').upload(path,proof,{contentType:proof.type});if(u.error)throw Error(u.error.message);await rpc('submit_proof',{p_report:selected.id,p_photo:path,p_note:note});setSelected(null);setProof(null);setMessage('Proof submitted for review.')})}>Submit collection proof</Button><Button variant="outline" disabled={busy} onClick={()=>action(async()=>{await rpc('transition_report',{p_report:selected.id,p_action:'blocked',p_note:note});setSelected(null)})}>Report blocker</Button></div>}
 {selected.status==='resolved'&&profile.role==='citizen'&&<Button disabled={busy} onClick={()=>action(async()=>{await rpc('transition_report',{p_report:selected.id,p_action:'reopened',p_note:note});setSelected(null)})}>Dispute closure</Button>}</>:<div className="empty"><MapPin/><h2>Select a report</h2><p>View its location, evidence, and recorded history.</p></div>}</section></div></>}</>}
 {page==='Rewards & impact'&&profile&&<><div className="cards">{[{label:'Verified points',value:points},{label:'Resolved reports',value:reports.filter(r=>r.status==='resolved').length},{label:'Reports submitted',value:reports.length}].map(c=><section className="panel" key={c.label}><Leaf/><h3>{c.label}</h3><h1>{c.value}</h1></section>)}</div><div className="soft">No weight, diversion or carbon estimate is available until quantities and destinations are recorded. Collection does not automatically mean recycling.</div></>}
 {page==='Profile & help'&&profile&&<section className="panel form"><label>Your display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><Button disabled={busy} onClick={()=>action(async()=>{await rpc('save_profile',{p_name:name,p_on_duty:profile.on_duty});setMessage('Profile saved.')})}>Save name</Button><p>Role: {profile.role}</p><label>Account ID for trusted setup<input readOnly value={uid}/></label><h2>Offline queue</h2><p>{queue.length} report(s) waiting on this browser</p><Button variant="outline" disabled={busy||queue.length===0} onClick={()=>action(sync)}>Synchronize now</Button><p>Keep this browser session. Account recovery and passkeys are not implemented yet.</p><p>Need collector access? Open the collector workspace and use the invitation provided by your administrator.</p></section>}
 </>;
}



